export * from "./schema";
export { createDb, getDb, type Database } from "./client";
export {
  getUserAuthSummary,
  getUserSettings,
  updateUserSettings,
  type UserAuthSummary,
  type UserSettings,
} from "./users";
export {
  countWatchesForUser,
  deleteWatchForUser,
  getWatchForUser,
  listWatchesForUser,
  saveWatch,
  updateWatchSettings,
  type SavedWatch,
  type SaveWatchResult,
} from "./watches";
export {
  getAlertClick,
  insertMatchIfNew,
  listAlertableWatches,
  listCoverageDueForPoll,
  listListingsByEbayItemIds,
  listUnsentMatchesForWatch,
  listWatchesForCoverage,
  listWatchIdsWithUnsentMatches,
  markCoveragePolled,
  recordAlerts,
  upsertListings,
  type CoverageToPoll,
  type StoredListing,
  type UnsentMatch,
  type WatchForAlert,
} from "./alerts";
export {
  incrementAgentSearchQuota,
  readAgentSearchQuota,
  writeAgentSearchQuota,
} from "./agent-quota";
export {
  getPaypalCatalogId,
  getSubscriptionByPaypalId,
  getUserSubscription,
  paypalCatalogKeyForId,
  savePaypalCatalogId,
  upsertUserSubscription,
  type UserSubscription,
} from "./subscriptions";
export {
  recordConsumerLogin,
  recordEbayApiCall,
  recordEmailSend,
  recordUserEvent,
  backfillUnauthenticatedCounts,
  ensureUnauthenticatedUser,
  isUnauthenticatedUserId,
  UNAUTHENTICATED_EMAIL,
  UNAUTHENTICATED_NAME,
  UNAUTHENTICATED_USER_ID,
  type EbayApiName,
  type EbayApiSource,
  type EmailKind,
  type EmailSendStatus,
  type UserEventKind,
} from "./telemetry";
export {
  maybeRunDailyPurge,
  RETENTION,
  type DailyPurgeResult,
  type PurgeDeleted,
} from "./purge";
export {
  processEbayAccountDeletion,
  listRecentEbayAccountDeletions,
  type AccountDeletionRecord,
} from "./account-deletion";
export {
  countUsers,
  ebayApiBreakdown,
  ebayApiDailyStats,
  ebayApiErrorGroups,
  ebayApiFailureCount,
  ebayApiStatusBreakdown,
  ebayApiWindowStats,
  emailBreakdown,
  emailWindowStats,
  fillEbayApiDays,
  getAdminUserDetail,
  listAdminUsers,
  listEbayApiFailures,
  parseEbayStatDay,
  parseEbayStatWindow,
  utcDayBounds,
  ADMIN_STATS_TIMEZONE,
  EBAY_FAILURE_PAGE_SIZE,
  EBAY_STAT_WINDOWS,
  type AdminUserDetail,
  type AdminUserListRow,
  type EbayApiBreakdownRow,
  type EbayApiDayRow,
  type EbayApiErrorGroup,
  type EbayApiFailureFilters,
  type EbayApiFailureRow,
  type EbayApiStatusRow,
  type EbayApiWindowStats,
  type EbayStatWindow,
  type EmailBreakdownRow,
  type EmailWindowStats,
} from "./admin";
